---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

  - name: debian-7.8
    driver_config:
      box: 'chef/debian-7.8'
    run_list:
      - recipe[runit]
    attributes:
      zookeeper:
        service_style: "runit"
      apache_kafka:
        service_style: "init.d"

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[zookeeper]
      - recipe[zookeeper::service]
      - recipe[apache_kafka]
    attributes:
      apt:
        compile_time_update: true
      apache_kafka:
        jmx:
          port: 9093
        service_style: "upstart"
      zookeeper:
        service_style: "upstart"
